import {randomUUID} from 'node:crypto'; import type {Change,Operation,Reversibility,Risk,Status,Transaction} from './types.js';
export const reversibility:Record<Operation,Reversibility>={UpdateAutoScalingGroup:'FULLY_REVERSIBLE',StopInstances:'COMPENSATABLE',TerminateInstances:'IRREVERSIBLE',UpdateService:'FULLY_REVERSIBLE',UpdateFunctionConfiguration:'FULLY_REVERSIBLE',DeleteFunction:'IRREVERSIBLE',PutRolePolicy:'PARTIALLY_REVERSIBLE',AttachRolePolicy:'PARTIALLY_REVERSIBLE',UpdateAssumeRolePolicy:'FULLY_REVERSIBLE',PutBucketPolicy:'PARTIALLY_REVERSIBLE',DeleteBucket:'IRREVERSIBLE'};
export const transitions:Record<Status,Status[]>={CREATED:['PLANNING'],PLANNING:['AWAITING_APPROVAL','APPROVED','BLOCKED','FAILED'],AWAITING_APPROVAL:['APPROVED','REJECTED'],APPROVED:['EXECUTING'],EXECUTING:['VERIFYING','FAILED'],VERIFYING:['COMMITTED','FAILED'],COMMITTED:['ROLLING_BACK'],REJECTED:[],BLOCKED:[],FAILED:[],ROLLING_BACK:['ROLLED_BACK','ROLLBACK_FAILED'],ROLLED_BACK:[],ROLLBACK_FAILED:[]};
export function transition(t:Transaction,to:Status,actor='system',message=`State changed to ${to}`){if(!transitions[t.status].includes(to))throw new Error(`Invalid transition ${t.status} -> ${to}`);t.status=to;t.updatedAt=new Date().toISOString();t.audit.push({id:randomUUID(),at:t.updatedAt,type:'STATE_CHANGED',actor,message});}
const title=(s:string)=>s.replace(/([A-Z])/g,' $1').trim();
export function hasWildcard(value:unknown):boolean{const walk=(item:unknown,policyField=false):boolean=>{if(typeof item==='string'){if(policyField&&item==='*')return true;try{return walk(JSON.parse(item),policyField)}catch{return false}}if(Array.isArray(item))return item.some(entry=>walk(entry,policyField));if(item&&typeof item==='object')return Object.entries(item).some(([key,entry])=>walk(entry,policyField||['Action','NotAction','Resource','NotResource'].includes(key)));return false;};return walk(value);}
export function semanticDiff(operation:Operation,before:Record<string,unknown>,after:Record<string,unknown>,env:string):Change[]{const changes:Change[]=[];for(const [field,value] of Object.entries(after)){if(JSON.stringify(before[field])===JSON.stringify(value))continue;let meaning=`${title(field)} changes from ${JSON.stringify(before[field])} to ${JSON.stringify(value)}.`;if(operation==='UpdateAutoScalingGroup'&&field==='desiredCapacity'&&typeof before[field]==='number'&&typeof value==='number'){const pct=Math.round((1-value/before[field])*100);meaning=`${env==='production'?'Production ':''}compute capacity ${pct>=0?'decreases':'increases'} by ${Math.abs(pct)}%.`}if(operation.includes('Policy')&&hasWildcard(value))meaning='This change may grant unrestricted AWS actions or resources.';changes.push({field,before:before[field],after:value,meaning});}return changes;}
export function assessRisk(input:{environment:string;operation:Operation;changes:Change[];reversibility:Reversibility;customerFacing:boolean;dependencies:string[]}):Risk{const reasons:Risk['reasons']=[];const add=(points:number,reason:string,evidence:string)=>reasons.push({points,reason,evidence});if(input.environment==='production')add(25,'Production resource','environment=production');if(['TerminateInstances','DeleteFunction','DeleteBucket'].includes(input.operation))add(30,'Destructive operation',input.operation);if(input.reversibility==='IRREVERSIBLE')add(25,'No reliable rollback',input.reversibility);if(input.customerFacing)add(15,'Customer-facing dependency','resource tags/dependency metadata');const capacity=input.changes.find(c=>c.field==='desiredCapacity');if(capacity&&typeof capacity.before==='number'&&typeof capacity.after==='number'&&capacity.after<capacity.before*.5)add(25,'Capacity reduction exceeds 50%',`${capacity.before} → ${capacity.after}`);if(['PutRolePolicy','AttachRolePolicy','UpdateAssumeRolePolicy'].includes(input.operation)&&input.changes.some(c=>hasWildcard(c.after)))add(100,'Wildcard privilege escalation','Action or Resource contains *');if(input.dependencies.length>2)add(10,'Wide blast radius',`${input.dependencies.length} linked resources`);if(input.reversibility==='FULLY_REVERSIBLE')add(-10,'Configuration rollback available','before state captured');const score=Math.max(0,Math.min(100,reasons.reduce((n,r)=>n+r.points,0)));return{score,level:score>=85?'CRITICAL':score>=60?'HIGH':score>=30?'MEDIUM':'LOW',reasons};}
export function policyFor(t:Pick<Transaction,'operation'|'environment'|'risk'|'reversibility'|'changes'>){if(['PutRolePolicy','AttachRolePolicy','UpdateAssumeRolePolicy'].includes(t.operation)&&t.changes.some(c=>hasWildcard(c.after)))return{decision:'BLOCK' as const,reason:'Wildcard IAM privilege escalation is prohibited'};if(t.environment==='development'&&t.risk.level==='LOW'&&t.reversibility==='FULLY_REVERSIBLE')return{decision:'AUTO_APPROVE' as const,reason:'Low-risk reversible development change'};return{decision:'REQUIRE_APPROVAL' as const,reason:t.environment==='production'?'Production changes require human approval':'Risk policy requires approval'};}
export function rollbackParams(t:Transaction){if(t.reversibility!=='FULLY_REVERSIBLE')throw new Error('Automated rollback is only available for fully reversible operations');const keys=Object.keys(t.params);return Object.fromEntries(keys.filter(k=>k in t.beforeState).map(k=>[k,t.beforeState[k]]));}
