import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {assessRisk, policyFor, reversibility, rollbackParams, semanticDiff, transition} from './engine.js';
import {operations, type Operation, type Status, type Transaction} from './types.js';
import type {Provider} from './aws.js';
import type {Store} from './store.js';

const name=z.string().min(1).max(256);
const jsonPolicy=z.union([z.string().min(2).max(131072).refine(v=>{try{JSON.parse(v);return true}catch{return false}},{message:'Policy must be valid JSON'}),z.record(z.string(),z.unknown())]);
export const operationParams:Record<Operation,z.ZodType<Record<string,unknown>>>= {
 UpdateAutoScalingGroup:z.object({autoScalingGroupName:name,minSize:z.number().int().nonnegative().optional(),maxSize:z.number().int().positive().optional(),desiredCapacity:z.number().int().nonnegative().optional()}).strict().refine(x=>x.minSize!==undefined||x.maxSize!==undefined||x.desiredCapacity!==undefined,'At least one capacity field is required').refine(x=>x.minSize===undefined||x.maxSize===undefined||x.minSize<=x.maxSize,'minSize cannot exceed maxSize'),
 StopInstances:z.object({instanceIds:z.array(name).min(1).max(1000)}).strict(), TerminateInstances:z.object({instanceIds:z.array(name).min(1).max(1000)}).strict(),
 UpdateService:z.object({cluster:name,service:name,desiredCount:z.number().int().nonnegative().optional(),taskDefinition:name.optional(),forceNewDeployment:z.boolean().optional()}).strict().refine(x=>Object.keys(x).length>2,'A service change is required'),
 UpdateFunctionConfiguration:z.object({functionName:name,memorySize:z.number().int().min(128).max(10240).optional(),timeout:z.number().int().min(1).max(900).optional(),runtime:name.optional(),environment:z.object({Variables:z.record(z.string(),z.string())}).strict().optional()}).strict().refine(x=>Object.keys(x).length>1,'A configuration change is required'),
 DeleteFunction:z.object({functionName:name}).strict(),
 PutRolePolicy:z.object({roleName:name,policyName:name,policyDocument:jsonPolicy}).strict(), AttachRolePolicy:z.object({roleName:name,policyArn:name}).strict(),
 UpdateAssumeRolePolicy:z.object({roleName:name,policyDocument:jsonPolicy}).strict(), PutBucketPolicy:z.object({bucket:name,policy:jsonPolicy}).strict(), DeleteBucket:z.object({bucket:name}).strict()
};
const baseProposal=z.object({idempotencyKey:z.string().min(8).max(128).regex(/^[A-Za-z0-9._:-]+$/),agent:z.string().min(1).max(80),sessionId:z.string().min(1).max(128),intent:z.string().min(3).max(500),operation:z.enum(operations),resource:name,environment:z.enum(['development','staging','production']),params:z.record(z.string(),z.unknown()),customerFacing:z.boolean().default(false),dependencies:z.array(name).max(100).default([])}).strict();
export const proposalSchema=baseProposal.transform((p,ctx)=>{const parsed=operationParams[p.operation].safeParse(p.params);if(!parsed.success){for(const issue of parsed.error.issues)ctx.addIssue({...issue,path:['params',...issue.path]});return z.NEVER;}return {...p,params:parsed.data};});
const errorMessage=(e:unknown,fallback:string)=>e instanceof Error?e.message:fallback;
export class TransactionService {
 constructor(private store:Store,private provider:Provider){}
 private async persist(t:Transaction, expectedStatuses?:Status[]){const version=t.version;await this.store.save(t,version,expectedStatuses);}
 async propose(raw:unknown,workspace='default'){
  const p=proposalSchema.parse(raw),now=new Date().toISOString();
  const t:Transaction={id:'AT-'+randomUUID().slice(0,8).toUpperCase(),version:0,workspaceId:workspace,...p,beforeState:{},expectedState:{},changes:[],risk:{score:0,level:'LOW',reasons:[]},policy:'REQUIRE_APPROVAL',policyReason:'Planning',reversibility:reversibility[p.operation],status:'CREATED',audit:[{id:randomUUID(),at:now,type:'PROPOSED',actor:p.agent,message:`Agent proposed ${p.operation}`}],createdAt:now,updatedAt:now};
  transition(t,'PLANNING'); const inserted=await this.store.create(t); if(!inserted.created)return inserted.transaction;
  try {t.beforeState=await this.provider.before(p.operation,p.params);t.audit.push({id:randomUUID(),at:new Date().toISOString(),type:'BEFORE_STATE_CAPTURED',actor:'system',message:'Normalized provider state captured'});t.expectedState={...t.beforeState,...p.params};t.changes=semanticDiff(t.operation,t.beforeState,t.expectedState,t.environment);t.risk=assessRisk(t);const policy=policyFor(t);t.policy=policy.decision;t.policyReason=policy.reason;transition(t,policy.decision==='BLOCK'?'BLOCKED':policy.decision==='AUTO_APPROVE'?'APPROVED':'AWAITING_APPROVAL','policy',policy.reason);await this.persist(t,['PLANNING']);return t;} catch(e){transition(t,'FAILED','system',errorMessage(e,'Planning failed'));await this.persist(t,['PLANNING']);return t;}
 }
 async decide(id:string,decision:'APPROVE'|'REJECT',approver:string,comment:string,workspace='default'){if(!approver.trim())throw new Error('Approver is required');const t=await this.must(id,workspace);if(t.status!=='AWAITING_APPROVAL')throw new Error('Transaction is not awaiting approval');t.approval={decision,approver:approver.slice(0,128),comment:comment.slice(0,1000),at:new Date().toISOString()};transition(t,decision==='APPROVE'?'APPROVED':'REJECTED',approver,`${decision}: ${comment||'No comment'}`);await this.persist(t,['AWAITING_APPROVAL']);return t;}
 async execute(id:string,workspace='default'){const t=await this.must(id,workspace);if(t.status==='COMMITTED'||t.status==='VERIFYING'||t.status==='EXECUTING')return t;if(t.status!=='APPROVED')throw new Error('Only approved transactions may execute');transition(t,'EXECUTING');t.execution={startedAt:new Date().toISOString()};await this.persist(t,['APPROVED']);let persistedStatus:Status='EXECUTING';try{const result=await this.provider.execute(t.operation,t.params);t.execution.providerRequestId=result.requestId;t.execution.completedAt=new Date().toISOString();transition(t,'VERIFYING');await this.persist(t,['EXECUTING']);persistedStatus='VERIFYING';t.actualState=await this.provider.before(t.operation,t.params);const ok=Object.entries(t.params).every(([k,v])=>JSON.stringify(t.actualState?.[k])===JSON.stringify(v));t.verification=ok?'VERIFIED':'VERIFICATION_FAILED';transition(t,ok?'COMMITTED':'FAILED','system',ok?'Execution and resulting state verified':'Provider succeeded but resulting state did not match the plan');}catch(e){t.execution.error=errorMessage(e,'Provider failure');const failedFrom=t.status as Status;if(failedFrom==='EXECUTING'||failedFrom==='VERIFYING')transition(t,'FAILED','system',t.execution.error);}await this.persist(t,[persistedStatus]);return t;}
 async rollback(id:string,workspace='default'){const t=await this.must(id,workspace);if(t.status==='ROLLED_BACK'||t.status==='ROLLING_BACK')return t;if(t.status!=='COMMITTED')throw new Error('Only committed transactions may roll back');const params=rollbackParams(t);transition(t,'ROLLING_BACK');await this.persist(t,['COMMITTED']);try{await this.provider.execute(t.operation,{...t.params,...params});const actual=await this.provider.before(t.operation,t.params);if(!Object.entries(params).every(([k,v])=>JSON.stringify(actual[k])===JSON.stringify(v)))throw new Error('Rollback verification did not match before state');t.actualState=actual;t.verification='VERIFIED';transition(t,'ROLLED_BACK','system','Compensating action verified');}catch(e){transition(t,'ROLLBACK_FAILED','system',errorMessage(e,'Rollback failed'));}await this.persist(t,['ROLLING_BACK']);return t;}
 async must(id:string,w:string){const t=await this.store.get(id,w);if(!t)throw new Error('Transaction not found');return t;}
}
